name: Version and Release

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build the Docker image
      run: docker build . --file FCorp.WebApi/Dockerfile --tag fcorpimage
      
    - name: Save Docker image
      run: docker image save fcorpimage:latest -o fcorpimage.tar
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "fcorpimage.tar"
        bodyFile: "body.md"